# Generated by Django 3.1.3 on 2021-01-19 15:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory_of_moments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moments',
            name='date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
