# Generated by Django 3.1.3 on 2021-01-19 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memory_of_moments', '0002_auto_20210119_2139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moments',
            old_name='date',
            new_name='dt',
        ),
    ]
