# Generated by Django 3.1.3 on 2021-01-19 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memory_of_moments', '0004_auto_20210119_2147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moments',
            old_name='content',
            new_name='contents',
        ),
    ]
