# Generated by Django 3.1.3 on 2021-01-19 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory_of_moments', '0005_auto_20210119_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moments',
            name='dt',
            field=models.DateField(auto_now_add=True),
        ),
    ]
